//QUESTAO PRESENTE NO SLIDE 02 DE DESENVOLVIMENTO DE APLICAÇÃO DESKTOP.
//QUESTÃO COMPOSTA POR DUAS CLASSES: MAIN, BANCOPORODUTOS.
//
//RESOLUÇÃO: SIMULAÇÃO DE UM BANCO DE DADOS DE VÁRIOS PRODUTOS, ONDE A FUNÇÃO DO MÉTODO É RETORNAR, SEPARADAMENTE, A LISTA GERAL DE PRODUTOS, PRODUTOS IMPORTADOS E NACIONAIS.
